/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.APIConnector;
import Controlador.DBConnector;
import Controlador.HibernateConnector;
import Controlador.MongoConnector;
import Modelo.Pelicula;
import com.mongodb.client.MongoDatabase;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import modelo.Personaje;

/**
 *
 * @author Argudo_Plomo
 */
public class Vista extends javax.swing.JFrame {
    
    APIConnector api = new APIConnector();
    MongoConnector mongo = new MongoConnector("mongodb://localhost:27017/");
    DBConnector sql = new DBConnector("BD_SW");
    HibernateConnector hibernate = new HibernateConnector();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        iniciarCheckBoxPeliculas();
    }

    private void iniciarCheckBoxPeliculas () {
        cbxPeliculas.removeAll();
        String[] peliculas;
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(hibernate.sabarTitulosDePeliculas());
        cbxPeliculas.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMongo = new javax.swing.JButton();
        lblAPIMongo = new javax.swing.JLabel();
        lblMongoHeidi = new javax.swing.JLabel();
        btnHeidi = new javax.swing.JButton();
        txtNameBDMongo = new javax.swing.JTextField();
        lblNombreBD = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnSecuelas = new javax.swing.JButton();
        lblMeterSecuelas = new javax.swing.JLabel();
        chboxEpisode1 = new javax.swing.JCheckBox();
        chboxEpisode2 = new javax.swing.JCheckBox();
        chboxEpisode3 = new javax.swing.JCheckBox();
        chboxEpisode4 = new javax.swing.JCheckBox();
        chboxEpisode5 = new javax.swing.JCheckBox();
        chboxEpisode6 = new javax.swing.JCheckBox();
        chboxEpisode7 = new javax.swing.JCheckBox();
        chboxEpisode8 = new javax.swing.JCheckBox();
        chboxEpisode9 = new javax.swing.JCheckBox();
        lblPrecuelas = new javax.swing.JLabel();
        lblOriginales = new javax.swing.JLabel();
        lblSecuelas = new javax.swing.JLabel();
        lblPersonaje = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtLugarNacimiento = new javax.swing.JTextField();
        lblLugarNacimiento = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbxPeliculas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersonajes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STAR WARS APP");
        setBackground(new java.awt.Color(51, 51, 51));

        btnMongo.setText("CARGAR MONGO");
        btnMongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMongoActionPerformed(evt);
            }
        });

        lblAPIMongo.setText("Cargar Mongo desde API:");

        lblMongoHeidi.setText("Cargar Heidi desde Mongo:");

        btnHeidi.setText("CARGAR HEIDI");
        btnHeidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeidiActionPerformed(evt);
            }
        });

        lblNombreBD.setText("Nombre de BD:");

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 0));
        lblTitulo.setText("STAR WARS");

        btnSecuelas.setText("CARGAR SECUELAS");
        btnSecuelas.setEnabled(false);
        btnSecuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecuelasActionPerformed(evt);
            }
        });

        lblMeterSecuelas.setText("Cargar secuelas en Heidi:");

        chboxEpisode1.setText("Episodio 1");

        chboxEpisode2.setText("Episodio 2");

        chboxEpisode3.setText("Episodio 3");

        chboxEpisode4.setText("Episodio 1");

        chboxEpisode5.setText("Episodio 5");

        chboxEpisode6.setText("Episodio 6");

        chboxEpisode7.setText("Episodio 7");

        chboxEpisode8.setText("Episodio 8");

        chboxEpisode9.setText("Episodio 9");

        lblPrecuelas.setText("Precuelas");

        lblOriginales.setText("Originales");

        lblSecuelas.setText("Secuelas");

        lblPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPersonaje.setText("Insertar Personaje");

        lblNombre.setText("Nombre:");

        lblFechaNacimiento.setText("Fecha de nacimiento:");

        lblGenero.setText("Genero:");

        lblLugarNacimiento.setText("Lugar de nacimiento:");

        lblPeso.setText("Peso:");

        lblAltura.setText("Altura (cm) :");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apariciones:");

        jButton1.setText("INSERTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbxPeliculas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPeliculasItemStateChanged(evt);
            }
        });

        lstPersonajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPersonajes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPersonajesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPersonajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(397, 397, 397))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPeso)
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLugarNacimiento)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaNacimiento)
                                    .addComponent(lblGenero)
                                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAltura)))
                            .addComponent(lblPersonaje))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chboxEpisode3)
                                    .addComponent(chboxEpisode2)
                                    .addComponent(chboxEpisode1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(lblPrecuelas)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chboxEpisode6)
                                    .addComponent(chboxEpisode5)
                                    .addComponent(chboxEpisode4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(lblOriginales)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chboxEpisode9)
                                    .addComponent(chboxEpisode8)
                                    .addComponent(chboxEpisode7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblSecuelas))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMongoHeidi)
                                .addComponent(lblAPIMongo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMeterSecuelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSecuelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHeidi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMongo)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreBD)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNameBDMongo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168)
                                        .addComponent(cbxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblNombreBD)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAPIMongo)
                    .addComponent(btnMongo)
                    .addComponent(txtNameBDMongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMongoHeidi)
                            .addComponent(btnHeidi))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSecuelas)
                            .addComponent(lblMeterSecuelas))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblPrecuelas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chboxEpisode1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chboxEpisode2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chboxEpisode3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSecuelas)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chboxEpisode7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chboxEpisode8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chboxEpisode9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblOriginales)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chboxEpisode4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chboxEpisode5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chboxEpisode6)))
                                        .addGap(2, 2, 2)))
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPersonaje)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblGenero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblFechaNacimiento)
                                            .addGap(28, 28, 28))
                                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLugarNacimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMongoActionPerformed
        deAPIaMongo(txtNameBDMongo.getText());
        btnMongo.setEnabled(false);
								//iniciarCheckBoxPeliculas();
    }//GEN-LAST:event_btnMongoActionPerformed

    private void btnHeidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeidiActionPerformed
        deMongoaHeidi(txtNameBDMongo.getText());
								iniciarCheckBoxPeliculas();
    }//GEN-LAST:event_btnHeidiActionPerformed

    private void btnSecuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecuelasActionPerformed
        hibernate.insertarSecuelas();
								iniciarCheckBoxPeliculas();
    }//GEN-LAST:event_btnSecuelasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = txtNombre.getText();
        String genero = txtGenero.getText();
        String fecha = txtFechaNacimiento.getText();
        String lugar = txtLugarNacimiento.getText();
        double peso = Double.parseDouble(txtPeso.getText());
        int altura = Integer.parseInt(txtAltura.getText());
        
        ArrayList<Pelicula> pelis = new ArrayList<>();
        if (chboxEpisode1.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(1));
        if (chboxEpisode2.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(2));
        if (chboxEpisode3.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(3));
        if (chboxEpisode4.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(4));
        if (chboxEpisode5.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(5));
        if (chboxEpisode6.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(6));
        if (chboxEpisode7.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(7));
        if (chboxEpisode8.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(8));
        if (chboxEpisode9.isSelected())
            pelis.add(hibernate.buscarPeliPorIDHib(9));
        
        Personaje personaje = new Personaje(nombre, genero, lugar, fecha, altura, peso, pelis);
        
        hibernate.insertarPersonaje(personaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxPeliculasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPeliculasItemStateChanged
        lstPersonajes.removeAll();
        
        DefaultListModel<String> modelo = new DefaultListModel<String>();
        int episode = cbxPeliculas.getSelectedIndex()+1;
        String[] personajes = hibernate.sacarNombresDePersonajesDePelicula(episode);
        
        for (int i = 0; i < personajes.length; i++) {
            modelo.add(i, personajes[i]);
        }
        
        lstPersonajes.setModel(modelo);
    }//GEN-LAST:event_cbxPeliculasItemStateChanged

    private void lstPersonajesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPersonajesValueChanged
        String nombre = lstPersonajes.getSelectedValue();
								Personaje p = hibernate.buscarPersonajePorNombre(nombre);
								
								txtNombre.setText(p.getNombre());
								txtGenero.setText(p.getGenero());
								txtLugarNacimiento.setText(p.getLugarNacimiento());
								txtFechaNacimiento.setText(p.getAnioNacimiento());
								txtAltura.setText(String.valueOf(p.getAltura()));
								txtPeso.setText(String.valueOf(p.getPeso()));
    }//GEN-LAST:event_lstPersonajesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHeidi;
    private javax.swing.JButton btnMongo;
    private javax.swing.JButton btnSecuelas;
    private javax.swing.JComboBox<String> cbxPeliculas;
    private javax.swing.JCheckBox chboxEpisode1;
    private javax.swing.JCheckBox chboxEpisode2;
    private javax.swing.JCheckBox chboxEpisode3;
    private javax.swing.JCheckBox chboxEpisode4;
    private javax.swing.JCheckBox chboxEpisode5;
    private javax.swing.JCheckBox chboxEpisode6;
    private javax.swing.JCheckBox chboxEpisode7;
    private javax.swing.JCheckBox chboxEpisode8;
    private javax.swing.JCheckBox chboxEpisode9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAPIMongo;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLugarNacimiento;
    private javax.swing.JLabel lblMeterSecuelas;
    private javax.swing.JLabel lblMongoHeidi;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreBD;
    private javax.swing.JLabel lblOriginales;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPrecuelas;
    private javax.swing.JLabel lblSecuelas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstPersonajes;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtLugarNacimiento;
    private javax.swing.JTextField txtNameBDMongo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables

    private void deAPIaMongo (String nameBD) {
        
        if (!(nameBD.length() > 0)) {
            nameBD = "SW_API";
            txtNameBDMongo.setText(nameBD);
        }
        
        ArrayList<Personaje> pers = api.cargarPersonajes();
        ArrayList<Pelicula> pels = api.cargarPeliculas();
        
        MongoDatabase db = mongo.createDB(nameBD);
        mongo.createCollectionPersonajes(db);
        mongo.createCollectionPersonajes(db);
        
        mongo.insertarPersonajes(db, pers);
        mongo.insertarPeliculas(db, pels);
    }
    
    private void deMongoaHeidi (String nameBD) {
        
        if (!(nameBD.length() > 0)) {
            nameBD = "SW_API";
            txtNameBDMongo.setText(nameBD);
        }
        
        MongoDatabase db = mongo.createDB(nameBD);
        ArrayList <Personaje> pers2 = mongo.cogerPersonajes(db);
        ArrayList <Pelicula> pels2 = mongo.cogerPeliculas(db);

        sql.insertarPersonajes(pers2);
        sql.insertarPeliculas(pels2);
        sql.insertarRelacionATravesDePeliculas(pels2);
        
        btnSecuelas.setEnabled(true);
    }
}
